const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const rules = fs.readFileSync(path.join(root, 'OPERATING_RULES.md'), 'utf8');
const app = fs.readFileSync(path.join(root, 'js/app.js'), 'utf8');
const background = fs.readFileSync(path.join(root, 'extension/background.js'), 'utf8');
const releaseScript = fs.readFileSync(path.join(root, 'scripts/release-domestic-collections.js'), 'utf8');
const dailyAuditWorkflow = fs.readFileSync(path.join(root, '.github/workflows/audit-daily-collections.yml'), 'utf8');
const commerceWorkflow = fs.readFileSync(path.join(root, '.github/workflows/sync-public-commerce-sources.yml'), 'utf8');
const inboxWorkflow = fs.readFileSync(path.join(root, '.github/workflows/merge-extension-inbox.yml'), 'utf8');
const inboxMergeScript = fs.readFileSync(path.join(root, 'scripts/merge-extension-inbox.js'), 'utf8');

test('the operating rulebook matches the primary collection architecture', () => {
  assert.match(rules, /data\/collections\.json`? 是收藏数据唯一的权威来源/);
  assert.match(rules, /提交 data\/inbox\/\*\.json/);
  assert.match(rules, /扩展不得在浏览器中直接读写整份 `data\/collections\.json`/);
  assert.match(rules, /GitHub Action 合并提交成功后，才是用户可见主站数据同步成功/);
  assert.match(rules, /30 分钟后由 GitHub Action 发布到国内站/);
  assert.match(rules, /具体状态页/);
  assert.match(rules, /只有 GitHub Action 合并提交成功才是主站同步成功/);
  assert.match(rules, /Grok CLI/);
  assert.match(rules, /GROK_CANDIDATE_FORMAT\.md/);
  assert.match(rules, /禁止使用浏览器自动操作 X/);
  assert.match(rules, /默认不启用定时运行/);
  assert.match(rules, /23:30.*Asia\/Shanghai/);
  assert.match(rules, /20 个汉字以内/);
  assert.match(rules, /titleSource.*manual/);
  assert.match(app, /PRIMARY_COLLECTIONS_URL/);
  assert.match(app, /getCollectionsRequestUrl/);
  assert.match(background, /queueAutomaticPrimarySync/);
  assert.match(background, /collectionSourceKey/);
  assert.match(background, /writeGitHubInboxBatch/);
  assert.match(background, /submittedToInbox: true/);
  assert.match(inboxWorkflow, /name: Merge Extension Inbox/);
  assert.match(inboxWorkflow, /data\/inbox\/\*\.json/);
  assert.match(inboxWorkflow, /node scripts\/merge-extension-inbox\.js --apply/);
  assert.match(inboxWorkflow, /node --test tests\/\*\.test\.js/);
  assert.match(inboxMergeScript, /function mergeExtensionInbox/);
  assert.match(inboxMergeScript, /githubSyncedAt: now/);
  assert.match(releaseScript, /30 \* 60 \* 1000/);
  assert.match(dailyAuditWorkflow, /cron: '30 15 \* \* \*'/);
  assert.match(dailyAuditWorkflow, /node scripts\/audit-daily-collections\.js --apply/);
  assert.match(dailyAuditWorkflow, /node --test tests\/\*\.test\.js/);
  assert.match(rules, /公开电商网站采集/);
  assert.match(rules, /commerce-public-sources\.json/);
  assert.match(rules, /04:17.*Asia\/Shanghai/);
  assert.match(commerceWorkflow, /cron: '17 20 \* \* \*'/);
  assert.match(commerceWorkflow, /node scripts\/sync-public-commerce-sources\.js --apply/);
  assert.match(commerceWorkflow, /node --test tests\/\*\.test\.js/);
});
